spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/sigesa}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sigesa}
    password: ${SPRING_DATASOURCE_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  reports:
    export-dir: ${APP_REPORTS_EXPORT_DIR:/tmp/sigesa-exports}
